---
  - include_tasks: copy-certificates.yml
  - include_tasks: flannel-configuration.yml
  - include_tasks: install-kubelet.yml
  - include_tasks: setup-kube-proxy-pod.yml
  - include_tasks: setup-worker-kubeconfig-pod.yml
  - include_tasks: systemd-reread.yml
  - include_tasks: run-flanneld.yml
  - include_tasks: start-kubelet.yml
