- name: Be sure that etcd has started
  wait_for:
    host: {{ groups.etcd_nodes | first }}
    port: 2379
- name: Configure flannel network in etcd - nodes
  uri:
    url: "http://{{ groups.etcd_nodes | first }}:2379/v2/keys/coreos.com/network/config"
    method: PUT
    body: "value={\"Network\":\"10.2.0.0/16\",\"Backend\":{\"Type\":\"vxlan\"}}"
    status: 201
    run_once: true
