- name: generate etcd-server certifcate
  command: kubeadm alpha phase certs etcd-server --config=/tmp/kubeadmcfg.yaml creates=/etc/kubernetes/pki/etcd/server.crt
- name: generate etcd-peer certifcate
  command: kubeadm alpha phase certs etcd-peer --config=/tmp/kubeadmcfg.yaml creates=/etc/kubernetes/pki/etcd/peer.crt
- name: generate etcd-healthcheck-client certifcate
  command: kubeadm alpha phase certs etcd-healthcheck-client --config=/tmp/kubeadmcfg.yaml creates=/etc/kubernetes/pki/etcd/healthcheck-client.crt
- name: generate apiserver-etcd-client certifcate
  command: kubeadm alpha phase certs apiserver-etcd-client --config=/tmp/kubeadmcfg.yaml creates=/etc/kubernetes/pki/apiserver-etcd-client.crt
- name: copy apiserver-etcd-client cert to local
  fetch:
    src: /etc/kubernetes/pki/apiserver-etcd-client.crt
    dest: /Users/erik/Development/opensource/kubernetes-cluster-runbook/certs/apiserver-etcd-client.crt
- name: copy apiserver-etcd-client key to local
  fetch:
    src: /etc/kubernetes/pki/apiserver-etcd-client.key
    dest: /Users/erik/Development/opensource/kubernetes-cluster-runbook/certs/apiserver-etcd-client.key