---
  - include_tasks: deploy-etcd-service-config.yml
  - include_tasks: deploy-kubeadm-config.yml
  - include_tasks: copy-ca.yml
  - include_tasks: generate-node-certificates.yml
  - include_tasks: create-manifest.yml
