- name: Create directory that contains the certificates
  file: path=/etc/kubernetes/ssl/ state=directory mode=0755
- name: Copy local ca certificate to kubernetes master
  copy:
    src: /Users/erik/Programming/terraform/kubernetes-cluster-runbook/certs/ca.pem
    dest: /etc/kubernetes/ssl/ca.pem
    mode: 0600
    owner: root
    group: root
- name: Copy local apiserver certificate to kubernetes master
  copy:
    src: /Users/erik/Programming/terraform/kubernetes-cluster-runbook/certs/apiserver.pem
    dest: /etc/kubernetes/ssl/apiserver.pem
    mode: 0600
    owner: root
    group: root
- name: Copy local apiserver key certificates to kubernetes master
  copy:
    src: /Users/erik/Programming/terraform/kubernetes-cluster-runbook/certs/apiserver-key.pem
    dest: /etc/kubernetes/ssl/apiserver-key.pem
    mode: 0600
    owner: root
    group: root
