- name: Create directory for pod manifests
  file: path=/etc/kubernetes/manifests state=directory mode=0755
- name: Deploy apiserver pod manifest
  template: src=kube-apiserver.yaml dest=/etc/kubernetes/manifests/kube-apiserver.yaml
